~/proj/lnrv/rtl/core/lnrv_def.v
#~/proj/lnrv/rtl/perips/lnrv_plic.v
#~/proj/lnrv/rtl/perips/lnrv_plmt.v
~/proj/lnrv/rtl/gen/lnrv_gnrl_buffer.v
~/proj/lnrv/rtl/gen/lnrv_icb2sram.v
~/proj/lnrv/rtl/gen/lnrv_gnrl_arbiter.v
~/proj/lnrv/rtl/gen/lnrv_icb_cmd_buf.v
~/proj/lnrv/rtl/gen/lnrv_gen_ram.v
#~/proj/lnrv/rtl/gen/lnrv_clk_gate.v
~/proj/lnrv/rtl/gen/lnrv_icb_buf.v
~/proj/lnrv/rtl/gen/lnrv_gnrl_fifo.v
~/proj/lnrv/rtl/gen/lnrv_icb_rsp_buf.v
#~/proj/lnrv/rtl/core/lnrsv_config.v
~/proj/lnrv/rtl/core/biu/lnrv_biu.v
~/proj/lnrv/rtl/core/top/lnrv_core.v
~/proj/lnrv/rtl/core/top/lnrv_cpu.v
~/proj/lnrv/rtl/core/ifu/lnrv_ifu_ifetch.v
~/proj/lnrv/rtl/core/ifu/lnrv_ifu.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_csr.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_debug.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_sys.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_excp.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_mdv.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_alu.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_disp.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_brch.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_rglr.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_cmt.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_irq.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_wbck.v
~/proj/lnrv/rtl/core/exu/lnrv_exu.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_lsu.v
~/proj/lnrv/rtl/core/exu/lnrv_exu_alu_mux.v
~/proj/lnrv/rtl/core/reg/lnrv_csr.v
~/proj/lnrv/rtl/core/reg/lnrv_gpr.v
~/proj/lnrv/rtl/core/idu/lnrv_idu.v
~/proj/lnrv/rtl/core/idu/lnrv_idu_decode.v
~/proj/lnrv/rtl/bus/lnrv_icb2axi.v
~/proj/lnrv/rtl/bus/lnrv_icb_mux.v
~/proj/lnrv/rtl/bus/lnrv_icb_demux.v
#~/proj/lnrv/rtl/bus/lnrv_axi2icb.v
#~/proj/lnrv/rtl/bus/lnrv_ahb2icb.v
#~/proj/lnrv/rtl/bus/lnrv_icb2ahb.v
#~/proj/lnrv/rtl/bus/lnrv_apb2icb.v
#~/proj/lnrv/rtl/soc/lnrv_soc.v
~/proj/lnrv/rtl/core/lnrv_undef.v